defaults: &defaults
  username: lcj7
  password: lcj7
  adapter: postgresql
  pool: 5
  encoding: utf8
  min_messages: warning

development:
  database: lcj7_dev
  <<: *defaults

test:
  database: lcj7_test
  <<: *defaults

production:
  <<: *defaults
  database: lcj7_production
  username: lcj7
  password: 'lcj7'